import { NextApiRequest, NextApiResponse, NextPage } from 'next'
import Head from 'next/head'
import connectToDatabase from '../mongodb'
import { COLLECTION_NAMES } from '../types'

export async function getServerSideProps (request: NextApiRequest) {
  const hash = request.query.hash as string
  const database = await connectToDatabase()
  const campaignCollection = database.collection(COLLECTION_NAMES['url-info'])
  const campaign = await campaignCollection.findOne({ uid: hash })

  if (campaign) {
    // Inkrementuj liczbę wejść w link
    await campaignCollection.updateOne(
      { _id: campaign._id },
      { $inc: { visits: 1 } }
    )

    return {
      redirect: {
        destination: campaign.link,
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}

const HashPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Requested link not found</h1>
    </div>
  )
}

export default HashPage
