import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shortener</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>URL shortener.</h1>
      <div>
        <h2>
          <a href='mailto:contact@blady.dev'>contact@blady.dev</a>
        </h2>
      </div>
    </div>
  )
}

export default Home
